### ISSUE TITLE
Lusas_Toolkit: Invalid name error when pushing lines grouped by mesh

### ISSUE THREAD

**Issue by ChrisSelf2** [BHoM/Lusas_Toolkit#171] opened 2019-05-23 15:00 UTC
When pushing surfaces having already pushed bars, the nextID function will give an id of a bar that already exists, hence not finding the highest one available. It implies that the element LusasID and Name are not alligned, i.e. the highest ID line does not have the highest numbered name.

**Comment by peterjamesnugent** [comment] 2019-05-24 07:55
@ChrisSelf2 I have had a look at this and I cannot reproduce your error. I can see the objects you pushed without SurfaceProperty or SectionProperty, so I created my own. When pushing with or without these properties I do not get an error.

One error I have seen in the past, is when you do not add a name for SectionProperty, SurfaceProperty and Material objects. The error does not come until much further downstream. 

I have attached my script on the link below, see if you can recreate the bug when not naming the properties.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Lusas_Toolkit/Lusas_Toolkit-%23171?csf=1&e=XnwzSw

**Comment by peterjamesnugent** [comment] 2019-05-28 11:49
The issue comes about because when bars are pushed they are grouped by their Mesh object, BarRelease and FEAType. 

`                var groupedBars = bars.GroupBy(m => new { m.FEAType, m.Release.Name, MeshSettings1D = m.CustomData["Mesh"] });`

Mesh 1 is applied to Line 1 and Line 3.
Mesh 2 is applied to Line 2.

Line 1 and Line 3 are pushed first, resulting in the LusasID (in the software) being 1 and 2 respectively.

The NextID works by finding the LargestID in the Lusas database and taking it's name to find the AdapterID.

The resulting set of lines can be summarised as follows:
Lusas name which is just L+AdapterID (Lusas database ID - which cannot be modified, hence the AdapterID is stored in the name).

L1 (1)
L3 (2)
L2 (3)

When a new line tries to be created, NextID will find get L2 (3), and will determine the highest AdapterID as 2. the line gets created and Lusas tries to assign the name as "L3", this causes an error because there is already an L3.

**Comment by peterjamesnugent** [comment] 2019-05-31 13:48
As discussed in weekly structural call:
- Override the NextID() by using the LargestLineID() COM call + 1

**Comment by peterjamesnugent** [comment] 2020-09-14 16:21
This should be fixed now because we no longer use `NextFreeId` and instead use the Lusas numbering.

**Closed by peterjamesnugent** 2020-09-14 16:21 UTC
Labels: severity:medium, size:S, type:bug
